[phases.setup]
nixPkgs = ["php83", "php83Extensions.pgsql", "php83Extensions.mbstring", "php83Extensions.xml", "php83Extensions.curl", "php83Extensions.zip", "php83Extensions.bcmath", "php83Extensions.tokenizer", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.deploy]
cmds = ["php artisan migrate --force", "php artisan config:clear", "php artisan route:clear", "php artisan view:clear"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
